language: python
language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt 
  - pip install coveralls
  - pip install coverage 
  - pip install nose

# command to run tests 
script: 
  # - nosetests --with-coverage --cover-package=app
  # - nosetests -v --with-coverage --cover-package="app"
  - coverage run -m nose

after_success: 
  - coveralls