language: python
python:
  - "3.6"

services:
  - postgresql

# command to install dependencies
install:
  - pip install -r requirements.txt 
  - pip install coveralls
  - pip install coverage 
  - pip install nose

# command to tell travis to install postgre db 
# and create a database fastFoodfast'''
before_script:
  - psql -c 'create database testdb;' -U postgres

# command to run tests 
script: 
  - nosetests --with-coverage --cover-package=app

after_success: 
  - coveralls
